version: '2'

volumes:
  data:
  logs:

services:
  app:
    image: theniwo/clonezilla:latest
    container_name: clonezilla
    hostname: clonezilla
    mem_limit: "512M"
    restart: unless-stopped
    privileged: true
    ports:
      - "2222:22"
    environment:
      - TERM=xterm
      - TZ=Europe/Berlin
    volumes:
      - /dev:/dev
      - /nfs/MyCloud/DATA/BACKUP/clonezilla:/home/partimag:shared
      - data:/root
      - logs:/var/log
